name: coUclient
author: coU Development Team
version: 0.0.0
homepage: ChildrenOfUr.github.io
description: The sourcecode/tools needed to hack/compile the Children of Ur client
dependencies:
  glitchTime:
    git:
      ref: master
      url: https://github.com/ChildrenOfUr/glitch-time.dart.git
  intl: any
  loadie:
    git:
      ref: master
      url: https://github.com/ChildrenOfUr/loadie.git
  pixi: any
  scproxy:
    git:
      ref: master
      url: https://github.com/darkkiero/scproxy.git
